#!/bin/sh
echo "[INFO] Hostname is "
hostname

echo "[INFO] **************************"
ls -ltr
echo "[INFO] **************************"
echo "[]INFO] current user is"
whoami

touch jenkins
echo "[INFO] **************************"
ls -ltr
echo "[INFO] **************************"
cat jenkins

echo "[INFO] **************************"
echo "insert into file" > jenkins

echo "[INFO] **************************"
cat jenkins

echo "[INFO] ***************************"
echo "[INFO] Demo for VCS polling for Jenkins"
echo "[INFO] ***************************"

echo "[INFO] Demo for Build trigger when other build is completed"
echo "[INFO] ***************************"
